#----- GDSC-tRAX v2 db Configuration File --------------#     
#-------------------------------------------------------#

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
genome: "mm10"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# MM10 tRNA DATABASE DOWNLOAD SETTINGS (NEED GENOME SPECIFIC CONFIGS)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
GTF_URL: "ftp://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz"
gtRNAdb_URL: "https://gtrnadb.ucsc.edu/genomes/eukaryota/Mmusc10/mm10-tRNAs.tar.gz"
gtRNAdb_OUT: "mm10-tRNAs-confidence-set.out"
gtRNAdb_NAME: "mm10-tRNAs_name_map.txt"
GENOME_URL: "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.2bit"
FASTA: "false"
makeDB: "code/new_make_database.py"
bt2_index: "tRNAgenome"